Improve error handling

diff --git a/home/.bash.d/symfony b/home/.bash.d/symfony
--- a/home/.bash.d/symfony
+++ b/home/.bash.d/symfony
@@ -8,7 +8,7 @@ __php_wrapper() {
   # check if a docker-compose.yml is present
   if [ -f "$GIT_ROOT/docker-compose.yml" ]; then
     PHP_CONTAINER=$(docker-compose ps | grep '_php_' | awk '{ print $1 }')
-    docker exec -u $(id -u) -it $PHP_CONTAINER $@
+    docker exec -u $(id -u) -it $PHP_CONTAINER php $@ 2> /dev/null || >&2 echo "$@: Command failed ($PHP_CONTAINER)"
   else
     php $@
   fi
